-- Learning Framework — Self-improving ML tables
-- Adds hypothesis tracking, experiment management, feature drift monitoring,
-- learning actions log, and config override tables.

-- Hypotheses generated by the hypothesis engine
CREATE TABLE IF NOT EXISTS hypotheses (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    hypothesis_id TEXT UNIQUE NOT NULL,
    category TEXT NOT NULL,
    statement TEXT NOT NULL,
    source TEXT NOT NULL,
    priority_score FLOAT8 DEFAULT 0,
    status TEXT DEFAULT 'pending',
    supporting_evidence JSONB DEFAULT '{}',
    effect_size FLOAT8,
    sample_size INT4,
    experiment_id TEXT,
    validation_result JSONB DEFAULT '{}',
    confidence_level TEXT,
    narrative TEXT,
    actionable_recommendation TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    validated_at TIMESTAMPTZ
);

-- Experiments designed and run by the experiment tracker
CREATE TABLE IF NOT EXISTS experiments (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    experiment_id TEXT UNIQUE NOT NULL,
    hypothesis_id TEXT,
    name TEXT NOT NULL,
    experiment_type TEXT NOT NULL,
    independent_variable TEXT NOT NULL,
    dependent_variable TEXT NOT NULL,
    control_group JSONB DEFAULT '{}',
    treatment_group JSONB DEFAULT '{}',
    min_sample_size INT4 DEFAULT 10,
    significance_level FLOAT8 DEFAULT 0.10,
    status TEXT DEFAULT 'pending',
    results JSONB DEFAULT '{}',
    control_metrics JSONB DEFAULT '{}',
    treatment_metrics JSONB DEFAULT '{}',
    effect_size FLOAT8,
    p_value FLOAT8,
    is_significant BOOLEAN DEFAULT FALSE,
    model_config JSONB DEFAULT '{}',
    model_results JSONB DEFAULT '{}',
    best_model_type TEXT,
    runtime_seconds FLOAT8,
    narrative TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    completed_at TIMESTAMPTZ
);

-- Feature drift detection log
CREATE TABLE IF NOT EXISTS feature_drift_log (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    feature_name TEXT NOT NULL,
    drift_type TEXT NOT NULL,
    current_mean FLOAT8,
    training_mean FLOAT8,
    current_std FLOAT8,
    training_std FLOAT8,
    drift_magnitude FLOAT8,
    is_significant BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Actions taken by the learning loop
CREATE TABLE IF NOT EXISTS learning_actions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    action_type TEXT NOT NULL,
    source_experiment_id TEXT,
    source_hypothesis_id TEXT,
    description TEXT NOT NULL,
    before_state JSONB DEFAULT '{}',
    after_state JSONB DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT now()
);

-- Regime-specific ensemble weight overrides (written by learning loop)
CREATE TABLE IF NOT EXISTS ensemble_weight_overrides (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    regime TEXT NOT NULL,
    signal_type TEXT NOT NULL,
    weight_multiplier FLOAT8 NOT NULL DEFAULT 1.0,
    source_experiment_id TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    UNIQUE(regime, signal_type)
);

-- Temporal position-sizing adjustments (written by learning loop)
CREATE TABLE IF NOT EXISTS temporal_adjustments (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    dimension TEXT NOT NULL,
    value INT4 NOT NULL,
    size_multiplier FLOAT8 NOT NULL DEFAULT 1.0,
    source_experiment_id TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    UNIQUE(dimension, value)
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_hypotheses_status ON hypotheses (status);
CREATE INDEX IF NOT EXISTS idx_hypotheses_category ON hypotheses (category);
CREATE INDEX IF NOT EXISTS idx_hypotheses_created ON hypotheses (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_experiments_status ON experiments (status);
CREATE INDEX IF NOT EXISTS idx_experiments_hypothesis ON experiments (hypothesis_id);
CREATE INDEX IF NOT EXISTS idx_experiments_created ON experiments (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_feature_drift_created ON feature_drift_log (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_feature_drift_feature ON feature_drift_log (feature_name);
CREATE INDEX IF NOT EXISTS idx_learning_actions_created ON learning_actions (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ensemble_overrides_regime ON ensemble_weight_overrides (regime);
CREATE INDEX IF NOT EXISTS idx_temporal_adj_dimension ON temporal_adjustments (dimension);

-- Enable RLS
ALTER TABLE hypotheses ENABLE ROW LEVEL SECURITY;
ALTER TABLE experiments ENABLE ROW LEVEL SECURITY;
ALTER TABLE feature_drift_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE learning_actions ENABLE ROW LEVEL SECURITY;
ALTER TABLE ensemble_weight_overrides ENABLE ROW LEVEL SECURITY;
ALTER TABLE temporal_adjustments ENABLE ROW LEVEL SECURITY;

-- Service role full access (backend)
CREATE POLICY "Service role full access" ON hypotheses FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access" ON experiments FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access" ON feature_drift_log FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access" ON learning_actions FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access" ON ensemble_weight_overrides FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access" ON temporal_adjustments FOR ALL USING (true) WITH CHECK (true);

-- Anon read access (dashboard)
CREATE POLICY "Anon read access" ON hypotheses FOR SELECT USING (true);
CREATE POLICY "Anon read access" ON experiments FOR SELECT USING (true);
CREATE POLICY "Anon read access" ON feature_drift_log FOR SELECT USING (true);
CREATE POLICY "Anon read access" ON learning_actions FOR SELECT USING (true);
CREATE POLICY "Anon read access" ON ensemble_weight_overrides FOR SELECT USING (true);
CREATE POLICY "Anon read access" ON temporal_adjustments FOR SELECT USING (true);
